### ISSUE TITLE
Cannot Authenticate

### ISSUE THREAD

**Issue by Guavaq** [Kjonge/PowerBIStravaConnector#9]
Hi there

When I try and authenticate I get the following error below.

![image](https://user-images.githubusercontent.com/31457981/67067439-c05bdb80-f1b9-11e9-9d40-43710aa592b4.png)

**Comment by mmassey10** [comment]
I am also receiving the same error.

**Comment by Guavaq** [comment]
Hi there

Kasper has updated the project.

I downloaded the latest version, rebuilt the MEZ file, added it to the location and it is now working for me.

**Comment by mmassey10** [comment]
It's working for me now. I was not aware that the redirect URL in Strava "OAuth.PowerBI.com" was case sensitive. It needs to be all lower case "oauth.powerbi.com"

**Comment by iBamse** [comment]
Hi,

Just downloaded the full project an hour ago. When trying to log in I first get a number of script errors, but am finally taken to the Strava login page. However, instead of being logged in I get the below error in Power BI:

![Annotation 2019-11-22 231618](https://user-images.githubusercontent.com/34922490/69464276-2a9a0a00-0d7e-11ea-9981-566f4ece7241.png)

**Comment by Guavaq** [comment]
It is working when I rebuilt it all from scratch
